### ISSUE TITLE
FC not working properly with user installed apps?

### ISSUE THREAD

**Issue by Project-Econome** [tryforge/ForgeCanvas#18]

**Comment by Project-Econome** [comment]
right so here is the issue
`module.exports = {
    data: {
        name: "book",
        description: "book",
        type: 1,
  
        integration_types: [1]
     },
    code: `
    
$createCanvas[meow;
    $setCanvasSize[1000;2000]
]
$drawImage[meow;./assets/page.jpg;0;0;1000;2000]

$attachCanvas[meow]

    `
}`

**Comment by Project-Econome** [comment]
![image](https://github.com/user-attachments/assets/de9ea4a1-5e69-4feb-a60a-6d0154a0c663)

**Comment by Project-Econome** [comment]
<@1096717977304453160>

**Comment by devlordduck** [comment]
are you sure this is a forge.canvas issue?

**Comment by Project-Econome** [comment]
> are you sure this is a forge.canvas issue?

im not too sure but idk if its a fc issue or a Forge issue so i just put it under fc its a user installed command

**Comment by Project-Econome** [comment]
> are you sure this is a forge.canvas issue?

also if you dont know alr i have left discord but am still coding

**Comment by devlordduck** [comment]
works fine for me

**Comment by Project-Econome** [comment]
> works fine for me

Hmm I'm not sure of the issue then can you help me?

**Comment by Project-Econome** [comment]
<@1096717977304453160> send me the code you used for me to test full code including module exports and also send me your index.js without token

**Comment by devlordduck** [comment]
$createCanvas[meow;
    $setCanvasSize[512;512]
    $fillStyle[;color;#FF0000]
    $drawRect[;fill;0;0;512;512]
]
$attachCanvas[meow;rawr.png]

**Comment by Project-Econome** [comment]
interesting but i need the $drawImage[meow;./assets/page.jpg;0;0;1000;2000] part working

**Comment by devlordduck** [comment]
its not working?

**Comment by devlordduck** [comment]
![meow](https://github.com/user-attachments/assets/c5c3a76d-1af0-4bf7-aad6-d2062d20ce49)

**Comment by Project-Econome** [comment]
> its not working?

im not sure why its not working its a jpg file and its directory is is assets/page.jpg

**Comment by devlordduck** [comment]
any errors?

**Comment by Project-Econome** [comment]
also is forge canvas supposed to come witout src folder? in node modules

**Comment by Project-Econome** [comment]
> any errors?

Unknown interaction on mine but works on your code but am going to test it on a command

**Comment by Project-Econome** [comment]
it all works except image function for some reason idk why

**Comment by Project-Econome** [comment]
wait i have found the problem its the way sizing is handled

**Comment by Project-Econome** [comment]
its a FC sizing issue not a me isssue

**Comment by Project-Econome** [comment]
try size 1000;2000

**Comment by devlordduck** [comment]
😐
![nyaaa](https://github.com/user-attachments/assets/5de7d44b-1449-4b91-86e6-f2f6f8498968)

**Comment by Project-Econome** [comment]
wat how is it working for you but not me -_-

**Comment by devlordduck** [comment]
skull issue

**Comment by Project-Econome** [comment]
ok anyways ty also if you need anything just send me a message in my git inbox

**Comment by Project-Econome** [comment]
also tell berk or aggelos to open up some sort of cross chatting page for forge so people who are github only like me now can open support tickets on a gh page

**Comment by aggelos-007** [comment]
brother just why can't u use fking discord when literally the whole project is based on discord

**Comment by Project-Econome** [comment]
> brother just why can't u use fking discord when u r literally the whole project is based on discord

im not on discord anymore -_- so i only read the errors i get in my logs an maintain my projects and hope for the best

**Comment by Project-Econome** [comment]
its like saying why make a mc based bot to get serveer data when i rarely/dont play minecraft its because i want to make a project for others to use and enjoy
